// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Z_wjTnkSrjJh2i8RykIlhPqVlHch6Nc',
    appId: '1:710584985805:web:ee52389c58af2033262184',
    messagingSenderId: '710584985805',
    projectId: 'railbook-10400',
    authDomain: 'railbook-10400.firebaseapp.com',
    storageBucket: 'railbook-10400.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjgH4MZWvpxKcvctH7PA3v9aCPyFbIgA',
    appId: '1:710584985805:android:6e9756abca6a94c0262184',
    messagingSenderId: '710584985805',
    projectId: 'railbook-10400',
    storageBucket: 'railbook-10400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxb7zWWQeljH01gcl8ebEU96d-ctSKgwk',
    appId: '1:710584985805:ios:acab2f64a3d8c4ef262184',
    messagingSenderId: '710584985805',
    projectId: 'railbook-10400',
    storageBucket: 'railbook-10400.appspot.com',
    iosBundleId: 'com.example.railBookPip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxb7zWWQeljH01gcl8ebEU96d-ctSKgwk',
    appId: '1:710584985805:ios:acab2f64a3d8c4ef262184',
    messagingSenderId: '710584985805',
    projectId: 'railbook-10400',
    storageBucket: 'railbook-10400.appspot.com',
    iosBundleId: 'com.example.railBookPip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Z_wjTnkSrjJh2i8RykIlhPqVlHch6Nc',
    appId: '1:710584985805:web:1b5015e2cec19928262184',
    messagingSenderId: '710584985805',
    projectId: 'railbook-10400',
    authDomain: 'railbook-10400.firebaseapp.com',
    storageBucket: 'railbook-10400.appspot.com',
  );
}
